# Generated by Django 3.2.9 on 2021-11-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_managacturer_manafacturer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manafacturer',
            new_name='Manufacturer',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='manafacturer',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='manufacturer',
            old_name='manafacturer_name',
            new_name='manufacturer_name',
        ),
    ]
