# Generated by Django 3.2.9 on 2021-11-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211102_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='manufacturer_image',
            field=models.ImageField(blank=True, upload_to='product/images/manufacturer/'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
