# Generated by Django 3.2.9 on 2021-12-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211102_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_name',
            new_name='title',
        ),
    ]
