# Generated by Django 3.2.9 on 2021-12-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20211215_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kcal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='nutrient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
