# Generated by Django 3.2.9 on 2021-12-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20211215_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
