# Generated by Django 3.2.9 on 2021-12-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
